experiment_name: 'IntegratedTraining'

description: "Complete Training Pipeline of the DPPD paper"

model: 
  n_layers: 16
  dim_in: 3 
  dim_feat: 128
  dim_rep: 512
  dim_out: 3
  mlp_ratio: 4
  act_layer: gelu
  attn_drop: 0.1
  drop: 0.1
  drop_path: 0.1
  use_layer_scale: True
  layer_scale_init_value: 0.00001
  use_adaptive_fusion: True
  num_heads: 8
  qkv_bias: False
  qkv_scale: null
  hierarchical: False
  use_temporal_similarity: True # Only useful when use_tcn = False
  neighbour_num: 2  # Only useful when use_temporal_similarity = True
  temporal_connection_len: 1 # Only useful when use_tcn = False, use_temporal_similarity = False
  use_tcn: False
  graph_only: False
  n_frames: 81

classifier:
  hidden_dim: 256
  dropout_rate: 0.2

mix2set:
  cs: 512
  dep: 8

dataset:
  pretraining: 
    path: datasets/preprocessed
    test_size: .2
  classification: datasets/CARE-PD/preprocessed/
  num_joints: 17
  num_classes: 4

training:
  batch_size: 8

  d3dp:
    number_of_frames: 81
    test_time_augmentation: false
    timesteps: 1000
    timesteps_eval: 1000 
    scale: 1.0

  pretraining:
    lr: 0.0004
    optimizer: adamw
    lambda_motion: 1
    joint_mask_ratio: 0.5
    frame_mask_ratio: 0.5
    epochs: 80
    save_freq: 20

  diffusion:
    lr: 0.001
    weight_decay: 0.1
    optimizer: adamw
    epochs: 80
    save_freq: 20

  classification:
    lr: 0.0004
    optimizer: adamw
    epochs: 10

checkpoints:
  backbone: assets/checkpoints/backbone_epoch_60.pth
  regressor: assets/checkpoints/regressor_epoch_60.pth
  d3dp: assets/checkpoints/d3dp_epoch_60.pth

save_path_root: 'v2'